class_name TestGrid

static func get_test_grid() -> Array[CellData]:
  return [
    CellData.EmptyCell.new(Vector2i(0, 0)),
    CellData.Wall.new(Vector2i(0, 1)),
    CellData.MonsterBat.new(Vector2i(0, 2)),
    CellData.MonsterSkeleton.new(Vector2i(0, 3)),
    CellData.MonsterMindFlayer.new(Vector2i(0, 4)),
    CellData.MonsterGargoyle.new(Vector2i(0, 5), CellData.MonsterGargoyle.Direction.RIGHT),
    CellData.MonsterGargoyle.new(Vector2i(0, 6), CellData.MonsterGargoyle.Direction.LEFT),
    CellData.MonsterGuardian.new(Vector2i(0, 7)),
    CellData.MonsterRat.new(Vector2i(0, 8), Vector2i(5, 7)),
    CellData.MonsterGargoyle.new(Vector2i(0, 9), CellData.MonsterGargoyle.Direction.RIGHT),
    CellData.MonsterGargoyle.new(Vector2i(0, 10), CellData.MonsterGargoyle.Direction.LEFT),
    CellData.EmptyCell.new(Vector2i(0, 11)),
    CellData.MonsterLich.new(Vector2i(0, 12)),
    CellData.EmptyCell.new(Vector2i(1, 0)),
    CellData.Wall.new(Vector2i(1, 1)),
    CellData.MonsterMine.new(Vector2i(1, 2)),
    CellData.Chest.new(Vector2i(1, 3), Vector2i(2, 2), CellData.Chest.Content.MONEY),
    CellData.MonsterRat.new(Vector2i(1, 4), Vector2i(5, 7)),
    CellData.MonsterRat.new(Vector2i(1, 5), Vector2i(5, 7)),
    CellData.MonsterGargoyle.new(Vector2i(1, 6), CellData.MonsterGargoyle.Direction.RIGHT),
    CellData.MonsterGargoyle.new(Vector2i(1, 7), CellData.MonsterGargoyle.Direction.LEFT),
    CellData.MonsterMine.new(Vector2i(1, 8)),
    CellData.MonsterSkeleton.new(Vector2i(1, 9)),
    CellData.MonsterBat.new(Vector2i(1, 10)),
    CellData.ScrollHealth.new(Vector2i(1, 11)),
    CellData.MonsterSlime.new(Vector2i(1, 12)),
    CellData.MonsterBat.new(Vector2i(2, 0)),
    CellData.ScrollHealth.new(Vector2i(2, 1)),
    CellData.MonsterMinotaur.new(Vector2i(2, 2), Vector2i(1, 3)),
    CellData.MonsterBat.new(Vector2i(2, 3)),
    CellData.MonsterGuardian.new(Vector2i(2, 4)),
    CellData.MonsterRat.new(Vector2i(2, 5), Vector2i(5, 7)),
    CellData.MonsterSkeleton.new(Vector2i(2, 6)),
    CellData.EmptyCell.new(Vector2i(2, 7)),
    CellData.EmptyCell.new(Vector2i(2, 8)),
    CellData.MonsterMine.new(Vector2i(2, 9)),
    CellData.MonsterMine.new(Vector2i(2, 10)),
    CellData.MonsterPurpleSlime.new(Vector2i(2, 11)),
    CellData.MonsterPurpleSlime.new(Vector2i(2, 12)),
    CellData.MonsterMindFlayer.new(Vector2i(3, 0)),
    CellData.EmptyCell.new(Vector2i(3, 1)),
    CellData.MonsterLover.new(Vector2i(3, 2), Vector2i(3, 10)),
    CellData.EmptyCell.new(Vector2i(3, 3)),
    CellData.MonsterMinotaur.new(Vector2i(3, 4), Vector2i(4, 3)),
    CellData.ScrollHealth.new(Vector2i(3, 5)),
    CellData.EmptyCell.new(Vector2i(3, 6)),
    CellData.MonsterBat.new(Vector2i(3, 7)),
    CellData.Chest.new(Vector2i(3, 8), Vector2i(4, 7), CellData.Chest.Content.HEALTH),
    CellData.EmptyCell.new(Vector2i(3, 9)),
    CellData.MonsterLover.new(Vector2i(3, 10), Vector2i(3, 2)),
    CellData.MonsterPurpleSlime.new(Vector2i(3, 11)),
    CellData.MonsterSlimeWitch.new(Vector2i(3, 12)),
    CellData.EmptyCell.new(Vector2i(4, 0)),
    CellData.Wall.new(Vector2i(4, 1)),
    CellData.EmptyCell.new(Vector2i(4, 2)),
    CellData.Chest.new(Vector2i(4, 3), Vector2i(3, 4), CellData.Chest.Content.MONEY),
    CellData.MonsterMine.new(Vector2i(4, 4)),
    CellData.MonsterSkeleton.new(Vector2i(4, 5)),
    CellData.MonsterDragon.new(Vector2i(4, 6)),
    CellData.MonsterMinotaur.new(Vector2i(4, 7), Vector2i(3, 8)),
    CellData.MonsterBat.new(Vector2i(4, 8)),
    CellData.MonsterRat.new(Vector2i(4, 9), Vector2i(5, 7)),
    CellData.EmptyCell.new(Vector2i(4, 10)),
    CellData.MonsterPurpleSlime.new(Vector2i(4, 11)),
    CellData.MonsterPurpleSlime.new(Vector2i(4, 12)),
    CellData.MonsterMine.new(Vector2i(5, 0)),
    CellData.Wall.new(Vector2i(5, 1)),
    CellData.MonsterSkeleton.new(Vector2i(5, 2)),
    CellData.MonsterMine.new(Vector2i(5, 3)),
    CellData.EmptyCell.new(Vector2i(5, 4)),
    CellData.EmptyCell.new(Vector2i(5, 5)),
    CellData.DragonEgg.new(Vector2i(5, 6)),
    CellData.MonsterRatKing.new(Vector2i(5, 7)),
    CellData.EmptyCell.new(Vector2i(5, 8)),
    CellData.EmptyCell.new(Vector2i(5, 9)),
    CellData.MonsterMinotaur.new(Vector2i(5, 10), Vector2i(6, 11)),
    CellData.MonsterSkeleton.new(Vector2i(5, 11)),
    CellData.MonsterSlime.new(Vector2i(5, 12)),
    CellData.MonsterBat.new(Vector2i(6, 0)),
    CellData.ScrollHealth.new(Vector2i(6, 1)),
    CellData.MonsterSlime.new(Vector2i(6, 2)),
    CellData.MonsterBat.new(Vector2i(6, 3)),
    CellData.MonsterRat.new(Vector2i(6, 4), Vector2i(5, 7)),
    CellData.MonsterSkeleton.new(Vector2i(6, 5)),
    CellData.EmptyCell.new(Vector2i(6, 6)),
    CellData.EmptyCell.new(Vector2i(6, 7)),
    CellData.MonsterRat.new(Vector2i(6, 8), Vector2i(5, 7)),
    CellData.MonsterMimic.new(Vector2i(6, 9)),
    CellData.EmptyCell.new(Vector2i(6, 10)),
    CellData.Chest.new(Vector2i(6, 11), Vector2i(5, 10), CellData.Chest.Content.MONEY),
    CellData.ScrollScrying.new(Vector2i(6, 12)),
    CellData.Wall.new(Vector2i(7, 0)),
    CellData.Wall.new(Vector2i(7, 1)),
    CellData.ScryingOrb.new(Vector2i(7, 2)),
    CellData.MonsterRat.new(Vector2i(7, 3), Vector2i(5, 7)),
    CellData.MonsterBat.new(Vector2i(7, 4)),
    CellData.EmptyCell.new(Vector2i(7, 5)),
    CellData.MonsterSlime.new(Vector2i(7, 6)),
    CellData.MonsterGuardian.new(Vector2i(7, 7)),
    CellData.MonsterSkeleton.new(Vector2i(7, 8)),
    CellData.MonsterBat.new(Vector2i(7, 9)),
    CellData.MonsterBat.new(Vector2i(7, 10)),
    CellData.MonsterSlime.new(Vector2i(7, 11)),
    CellData.EmptyCell.new(Vector2i(7, 12)),
    CellData.MonsterGuardian.new(Vector2i(8, 0)),
    CellData.MonsterRat.new(Vector2i(8, 1), Vector2i(5, 7)),
    CellData.EmptyCell.new(Vector2i(8, 2)),
    CellData.MonsterSkeleton.new(Vector2i(8, 3)),
    CellData.MonsterRat.new(Vector2i(8, 4), Vector2i(5, 7)),
    CellData.MonsterRat.new(Vector2i(8, 5), Vector2i(5, 7)),
    CellData.MonsterRat.new(Vector2i(8, 6), Vector2i(5, 7)),
    CellData.EmptyCell.new(Vector2i(8, 7)),
    CellData.MonsterMine.new(Vector2i(8, 8)),
    CellData.ScrollHealth.new(Vector2i(8, 9)),
    CellData.MonsterSkeleton.new(Vector2i(8, 10)),
    CellData.MonsterSlime.new(Vector2i(8, 11)),
    CellData.MonsterRat.new(Vector2i(8, 12), Vector2i(5, 7)),
    CellData.MonsterBat.new(Vector2i(9, 0)),
    CellData.Chest.new(Vector2i(9, 1), Vector2i(9, 2), CellData.Chest.Content.HEALTH),
    CellData.MonsterMinotaur.new(Vector2i(9, 2), Vector2i(9, 1)),
    CellData.EmptyCell.new(Vector2i(9, 3)),
    CellData.MonsterSlime.new(Vector2i(9, 4)),
    CellData.EmptyCell.new(Vector2i(9, 5)),
    CellData.MonsterMine.new(Vector2i(9, 6)),
    CellData.EmptyCell.new(Vector2i(9, 7)),
    CellData.MonsterSlime.new(Vector2i(9, 8)),
    CellData.EmptyCell.new(Vector2i(9, 9)),
    CellData.EmptyCell.new(Vector2i(9, 10)),
    CellData.MonsterGargoyle.new(Vector2i(9, 11), CellData.MonsterGargoyle.Direction.RIGHT),
    CellData.MonsterGargoyle.new(Vector2i(9, 12), CellData.MonsterGargoyle.Direction.LEFT),
  ]